# Generated by Django 3.1.4 on 2021-04-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20210408_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_first_login',
            field=models.BooleanField(null=True),
        ),
    ]
