# Generated by Django 3.1.5 on 2021-01-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sno', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('sname', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sex', models.IntegerField(choices=[(0, 'Woman'), (1, 'Man')], default=1)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
